### ISSUE TITLE
Incorporate custom CP/M diskdefs into scripts directly?

### ISSUE THREAD

**Issue by baljemmett** [AkBKukU/gw-tools#5]
I noticed when working on this evening's support for the Zobex CP/M formats that `cpmtools` claims to support taking an arbitrary diskdef on the command line, in addition to looking them up by name in the system-wide `diskdefs` file.  Quoting the `cpm(5)` manpage:

> *Format descrptions*
>
> CP/M format may be specified by either the format name in a diskdefs file, or by including the entire "diskdef" format.  For example:
>
>              -f name
>              -f `cat mydiskdef`
>              -f "diskdef; seclen 512; tracks 512; ... end"
>
> A single diskdef must not begin with a comment, in other words it must begin with "diskdef". The name is not required.

Would it make sense if we made use of this ability to specify diskdefs directly in the various `gw-cpm.*` scripts that need them, rather than the current approach of embedding one in a comment to be copied and pasted into the global configuration?

I'd be happy to spend a little while going through and doing this if you think it's worthwhile!

**Comment by AkBKukU** [comment]
Definitely, I hate the current solution and didn't know we could do that. That CLI format doesn't seem super easy to edit though, if it's possible to have in a variable or something easier to  that gets rebuilt into the CLI options that could be nice. The functions for that could go in `gw-raw` to be available to all scripts that need it.

**Comment by baljemmett** [comment]
I just tried a quick experiment by changing (tweaking, really) the embedded diskdef comment in `gw-cpm.zobex-dsdd` into this syntax:
```# uses custom diskdef:
# # ZOBEX DD-FDC controller, DSDD media
# # per CP/M V2.2 CBIOS for ZOBEX DD-FDC controller (30-Sep-81)
cpm_format="diskdef
   seclen 512
   tracks 154
   sectrk 16
   maxdir 256
   blocksize 4096
   skew 0
   boottrk 2
   os 2.2
end"
```

... and then changing `-f $format` to `-f "$cpm_format"` throughout the `extract` function, and it seems to work - does that strike a good balance, do you think?  If so, we could then consider moving the `extract` function out into a common `gw-cpm` script and have the various system-specific ones source it, passing either a diskdef name or a block like the above in as a parameter.

**Comment by AkBKukU** [comment]
That variable method seems good to me!

I would rather the extract function be in the scripts, all the PC floppy ones use the same commands for FAT 12 plus tons of other systems. It's just bash so it's like like we are gaining anything from really well optimizing it, so I'd rather make it more clear what it is doing for each system/format.

**Comment by baljemmett** [comment]
OK, that's fair enough!  I'll aim to submit a PR tomorrow with just the diskdef-embedding changes for all the CP/M systems, then.

**Comment by AkBKukU** [comment]
Solved with merge
